name: tahti

services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    image: tahti/website:latest
    container_name: tahti-website
    restart: unless-stopped
    ports:
      - "8090:80"
    networks:
      - internal

networks:
  internal:
    name: tahti_net
    driver: bridge
