// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Tahti ry <https://tahti.live>

import type { Job } from 'bullmq'
import { prisma } from '@tahti/db'
import {
  createBranch,
  createPullRequest,
  getDefaultBranchSha,
  getFileContent,
  putFileContent,
} from '../lib/github-api.js'
import { buildRegistryThemeFile, registryThemeSlug } from '../lib/registry-theme-file.js'

export interface OpenThemePullRequestPayload {
  themeId: string
}

export async function processOpenThemePullRequestJob(job: Job): Promise<void> {
  const { themeId } = job.data as OpenThemePullRequestPayload

  const theme = await prisma.theme.findUnique({
    where: { id: themeId },
    include: { user: { select: { username: true, displayName: true } } },
  })
  if (!theme) throw new Error(`Theme not found: ${themeId}`)

  try {
    const baseSlug = registryThemeSlug(theme.name)
    const idSuffix = theme.id.slice(0, 8).toLowerCase()
    const branchName = `theme/${baseSlug}-${idSuffix}`

    const baseSha = await getDefaultBranchSha()
    await createBranch(branchName, baseSha)

    // The catalog already has themes; a second one with the same name gets its
    // own file instead of overwriting (or failing against) the first.
    const taken = await getFileContent(`themes/${baseSlug}.json`, branchName)
    const themeFilePath = `themes/${taken ? `${baseSlug}-${idSuffix}` : baseSlug}.json`

    const themeContent =
      JSON.stringify(
        buildRegistryThemeFile({
          name: theme.name,
          author: theme.user.displayName || theme.user.username,
          varsJson: theme.varsJson,
          darkJson: theme.darkJson,
        }),
        null,
        2,
      ) + '\n'

    await putFileContent(
      themeFilePath,
      branchName,
      themeContent,
      `Add theme "${theme.name}" by @${theme.user.username}`,
      null,
    )

    const prUrl = await createPullRequest(
      branchName,
      `Add theme: ${theme.name}`,
      [
        `Submitted by @${theme.user.username} via the in-app theme editor, approved by an admin.`,
        '',
        `- Adds \`${themeFilePath}\``,
        '- `themes.json` is regenerated by the Build Theme Index workflow after merge',
        '',
        'Merging this PR publishes the theme to the Tahti Player Store.',
      ].join('\n'),
    )

    await prisma.theme.update({
      where: { id: themeId },
      data: { prStatus: 'OPENED', prUrl },
    })
  } catch (err) {
    await prisma.theme.update({ where: { id: themeId }, data: { prStatus: 'ERROR' } })
    throw err
  }
}
